name: Linux

on:
  [push, pull_request]

jobs:
  linux_build:
    name: Build ans Run (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sh scripts/linux/0_install_ubuntu.sh
    - name: Build 4AxisMilling
      run: |
        sh scripts/linux/1_build.sh
