name: Linux

on:
  [push, pull_request]

jobs:
  linux_build:
    name: Build ans Run (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sh scripts/linux/0_install_ubuntu.sh
    - name: Build 4AxisMilling
      run: |
        sh scripts/linux/1_build.sh
    - name: Run 4AxisMilling
      run: |
        sh scripts/linux/2_run_paper_results.sh
    - name: Upload Paper Results
      uses: actions/upload-artifact@v1
      with:
        name: paper_results_linux
        path: results
