name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name:
    - name: Install dependencies
      run: |
        sh scripts/linux/0_install_ubuntu.sh
    - name: Build 4AxisMilling
      run: |
        sh scripts/linux/1_build.sh
